// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// program //
// ------- //

#define program_wrap_target 0
#define program_wrap 5
#define program_pio_version 0

static const uint16_t program_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0xe03f, //  1: set    x, 31                      
    0x1e42, //  2: jmp    x--, 2                 [30]
    0xe000, //  3: set    pins, 0                    
    0xe03f, //  4: set    x, 31                      
    0x1e45, //  5: jmp    x--, 5                 [30]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program program_program = {
    .instructions = program_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config program_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + program_wrap_target, offset + program_wrap);
    return c;
}
#endif

